services:
  db:
    image: vs:latest
    container_name: vs-cont
    restart: always
    environment:
      POSTGRES_USER: "main_db"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "main_db"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - 2345:5432
      - 50:50
    volumes:
      - ./psql_data:/var/lib/postgresql/

volumes:
  psql_data: