services:
  web_app:
    image: vs-access-panel:latest
    container_name: vs-access-panel
    environment:
      ADMIN_LOGIN: "web-admin"
      ADMIN_PASSWORD: "secret123"
      APP_KEY: "uy578lhkg"
    ports:
      - 50170:50170
    volumes:
      - ./vs_access_panel.sqlite3:/app/vs_access_panel.sqlite3