services:
  web_app:
    image: vs:latest
    container_name: flask_app
    environment:
      ADMIN_LOGIN = "web-admin"
      ADMIN_PASSWORD = "secret123"
    ports:
      - 50170:50170
    volumes:
      - ./py_scripts/vs_access_panel.sqlite3: /app/py_scripts/vs_access_panel.sqlite3